### ISSUE TITLE
Headlines are too long

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/12characters-translations#12]
Some of the headlines are too long for the headings.

**Comment by niccokunzmann** [comment]
470d865492d40d56ab2982897eb4bfed8ca8dda3 - does not work

**Comment by jasonestewart** [comment]
This works:

https://latex.org/forum/viewtopic.php?f=59&t=25722&sid=542a1af47fed7009935a5f0566cad6cb#

**Comment by niccokunzmann** [comment]
#18 fixes this. Thanks for the contribution! Looks good!
